export default {
    CATEGORY: 'CATEGORY',
  COMMENT: 'COMMENT',
  MEDIA: 'MEDIA',
  PAGE: 'PAGE',
  POST: 'POST',
  POST_REVISION: 'POST_REVISION',
  POST_TYPE: 'POST_TYPE',
  POST_STATUS: 'POST_STATUS',
  TAG: 'TAG',
  TAXONOMY: 'TAXONOMY',
  USER: 'USER'
};
